# Generated by Django 3.2.15 on 2022-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='orderid',
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
